import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/common/Header";


const poppins = Poppins({
  subsets: ["latin"], weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], // Use 'weight' instead of 'weights' });
});

  export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };

  export default function RootLayout({ children }) {
  return(
    <html lang = "en" >
      <body
        className={`${poppins.className}  antialiased`}
      >

        <Header />
        {children}
      </body>
    </html >
  );
}
